namespace AIMultiAgentPlatform.Contracts.Intake;

public sealed record TallySubmissionRequest(
    string ExternalSubmissionId,
    string BusinessName,
    string PrimaryContactName,
    string PrimaryContactEmail,
    string Niche,
    string Offer = "",
    string TargetAudience = "",
    string BrandTone = "",
    string CallToActionKeyword = "",
    IReadOnlyList<string>? Platforms = null,
    IReadOnlyList<string>? PainPoints = null,
    IReadOnlyList<string>? Objections = null,
    IReadOnlyList<string>? AvoidTopics = null,
    int BacklogWindowDays = 14,
    string PrimaryContactPhone = "",
    string MainGoal = "",
    string MainOffer = "",
    string IdealClientDescription = "",
    string DesiredAction = "",
    string BrandTonePreference = "",
    string ContentLanguage = "",
    string InstagramUrl = "",
    string FacebookPageUrl = "",
    string TikTokUrl = "",
    string LinkedInUrl = "",
    string YouTubeShortsUrl = "",
    string CalendlyUrl = "",
    string PainPointsText = "",
    string ObjectionsText = "",
    string AvoidTopicsText = "");
